ConsultaMEdica/Controllers/SeguroesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConsultaMEdica.Models;

namespace ConsultaMEdica.Controllers
{
    public class SeguroesController : Controller
    {
        private ConsultaMedicaEntities db = new ConsultaMedicaEntities();

        // GET: Seguroes
        public ActionResult Index()
        {
            return View(db.Seguroes.ToList());
        }

        // GET: Seguroes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seguro seguro = db.Seguroes.Find(id);
            if (seguro == null)
            {
                return HttpNotFound();
            }
            return View(seguro);
        }

        // GET: Seguroes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Seguroes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nombre,Descripcion,Direccion,Telefono,Email")] Seguro seguro)
        {
            if (ModelState.IsValid)
            {
                db.Seguroes.Add(seguro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(seguro);
        }

        // GET: Seguroes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seguro seguro = db.Seguroes.Find(id);
            if (seguro == null)
            {
                return HttpNotFound();
            }
            return View(seguro);
        }

        // POST: Seguroes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Descripcion,Direccion,Telefono,Email")] Seguro seguro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seguro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seguro);
        }

        // GET: Seguroes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seguro seguro = db.Seguroes.Find(id);
            if (seguro == null)
            {
                return HttpNotFound();
            }
            return View(seguro);
        }

        // POST: Seguroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seguro seguro = db.Seguroes.Find(id);
            db.Seguroes.Remove(seguro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConsultaMEdica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    <!-- Favicon -->
    <link type="image/x-icon" href="favicon.png" rel="shortcut icon" />
    <!-- google font libraries -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
        <script src="Content/js/html5shiv.js"></script>
        <script src="Content/js/respond.min.js"></script>
    <![endif]-->
   

</head>
<body>
    <div id="theme-wrapper">
        <header class="navbar" id="header-navbar">
            <div class="container">
                <a href="index.html" id="logo" class="navbar-brand">
                    <img src="img/logo.png" alt="" class="normal-logo logo-white" />
                    <img src="img/logo-black.png" alt="" class="normal-logo logo-black" />
                    <img src="img/logo-small.png" alt="" class="small-logo hidden-xs hidden-sm hidden" />
                </a>

                <div class="clearfix">
                    <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="fa fa-bars"></span>
                    </button>

                    <div class="nav-no-collapse navbar-left pull-left hidden-sm hidden-xs">
                        <ul class="nav navbar-nav pull-left">
                            <li>
                                <a class="btn" id="make-small-nav">
                                    <i class="fa fa-bars"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="nav-no-collapse pull-right" id="header-nav">
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                            {
                                @Html.AntiForgeryToken()

                                <ul class="nav navbar-nav navbar-right">
                                    <li>
                                        @Html.ActionLink("Perfil", "Index", "Home", routeValues: null, htmlAttributes: new { title = "Perfil" })
                                    </li>
                                    <li><a href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a></li>
                                </ul>
                            }
                        }
                        else
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li>@Html.ActionLink("Registrarse", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                <li>@Html.ActionLink("Iniciar sesión", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                            </ul>
                        }
                    </div>
                </div>
            </div>
        </header>
        <div id="page-wrapper" class="container">
            <div class="row">
                <div id="nav-col">
                    <section id="col-left" class="col-left-nano">
                        <div id="col-left-inner" class="col-left-nano-content">
                            <div id="user-left-box" class="clearfix hidden-sm hidden-xs dropdown profile2-dropdown">
                                
                            </div>
                            <div class="collapse navbar-collapse navbar-ex1-collapse" id="sidebar-nav">
                                <ul class="nav nav-pills nav-stacked">
                                    <li class="nav-header nav-header-first hidden-sm hidden-xs">
                                        Navigation
                                    </li>
                                    @if (Request.IsAuthenticated)
                                    {
                                        <li class="active">
                                            @Html.ActionLink("Perfil", "Index", "Home", routeValues: null, htmlAttributes: new { title = "Perfil" })
                                        </li>
                                        <li class="active">
                                            @Html.ActionLink("Pacientes", "Index", "Pacientes", routeValues: null, htmlAttributes: new { title = "Pacientes" })
                                        </li>
                                        <li class="active">
                                            @Html.ActionLink("Seguros", "Index", "Seguroes", routeValues: null, htmlAttributes: new { title = "Seguros" })
                                        </li>
                                    }
                                    @*Enlaces temporal*@
                                    <li class="active">
                                        @Html.ActionLink("Pacientes", "Index", "Pacientes", routeValues: null, htmlAttributes: new { title = "Pacientes" })
                                    </li>   
                                    <li class="active">
                                        @Html.ActionLink("Seguros", "Index", "Seguroes", routeValues: null, htmlAttributes: new { title = "Seguros" })
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </section>
                    <div id="nav-col-submenu"></div>
                </div>
                <div id="content-wrapper">
                    <div class="row">
                        <div class="col-lg-12">

                            <div class="row">
                                <div class="col-lg-12">
                                    <ol class="breadcrumb">
                                        <li><a href="#">Home</a></li>
                                        <li class="active"><span>Dashboard</span></li>
                                    </ol>

                                    <h1>Dashboard</h1>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="main-box clearfix">
                                        <header class="main-box-header clearfix">
                                        </header>

                                        <div class="main-box-body clearfix">
                                           @RenderBody()
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <footer id="footer-bar" class="row">
                        <p id="footer-copyright" class="col-xs-12">
                            @DateTime.Now.Year
                        </p>
                    </footer>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Content/js/jquery.js"></script>
    @Scripts.Render("~/bundles/bootstrap")

    <!-- global scripts -->
    
    <script src="~/Content/js/jquery.nanoscroller.min.js"></script>
    <script src="~/Content/js/demo.js"></script> <!-- only for demo -->
    <!-- theme scContent/ripts -->
    <script src="~/Content/js/scripts.js"></script>
    <script src="~/Content/js/pace.min.js"></script>
    <!-- this page specific scripts -->
    <script src="~/Content/js/jquery.dataTables.js"></script>
    <script src="~/Content/js/dataTables.fixedHeader.js"></script>
    <script src="~/Content/js/dataTables.tableTools.js"></script>
    <script src="~/Content/js/jquery.dataTables.bootstrap.js"></script>
    @RenderSection("scripts", required: false)



    <script>
    $(document).ready(function () {
        var table = $('#table').dataTable({
            'info': false,
            'sDom': 'lTfr<"clearfix">tip',
            'oTableTools': {
                'aButtons': [
                    {
                        'sExtends': 'collection',
                        'sButtonText': '<i class="fa fa-cloud-download"></i>&nbsp;&nbsp;&nbsp;<i class="fa fa-caret-down"></i>',
                        'aButtons': ['csv', 'xls', 'pdf', 'copy', 'print']
                    }
                ]
            }
        });

        var tt = new $.fn.dataTable.TableTools(table);
        $(tt.fnContainer()).insertBefore('div.dataTables_wrapper');

        var tableFixed = $('#table-example-fixed').dataTable({
            'info': false,
            'pageLength': 50
        });

        new $.fn.dataTable.FixedHeader(tableFixed);
    });
    </script>
</body>
</html>